on:
  push:
    branches:
      - main

name: check

jobs:
  check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'devel'}

    steps:
      - uses: actions/checkout@v2

      - name: Search
        run: |
          brew install abseil

      - name: Search 2
        run: |
          pkg-config --libs abseil

      - name: Search 3
        run: |
          pkg-config --libs abseil-cpp

