on:
  push:
    branches:
      - main

name: check

jobs:
  check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'devel'}

    steps:

      - name: Session info
        run: |
          Sys.info()
        shell: Rscript {0}

